Refactor
Teaching-projects/SZE-MOSZE-2020-NullPointerException pull request #11
Opened 2020-11-05 18:54 UTC by gradden

@hegyhati Elkészültem a refactoring feladatrésszel. Hozzáadtam az új függvényekhez a dokumentációt és elkészítettem a hozzá tartozó diff/unit testeket is. 
A `units/results.txt` tartalmazza a feladat által megadott scenario fájlok tesztjeit, ahogy az a megadott `output1.txt output2.txt` + az egyedileg készített teszteket is egyaránt tartalmazza.

2020-11-06 13:00 UTC, hegyhati requested changes
Azt a template fuggvenyt tisztazzatok le,  igy eleg nagy katyvasz. Amugy jonak tunik.

2020-11-06 13:00 UTC, hegyhati commented on JSON.h
> +        return std::any_cast<T>(converted);
na ezt gondold at, osszevissza castolgatsz itt any meg "rendes tipusok" kozott oda-vissza feleslegesen.

2020-11-06 14:02 UTC, gradden commented on JSON.h
> +        return std::any_cast<T>(converted);
@hegyhati Igen tudom, de sajnos ha csak simán `return std::any_cast<t>(map[key]);` használok, akkor `std::bad_any_cast` hibát dob ki. De az istenért nem tudok rájönni, hogy mi okozza ezt a problémát, másoknál pedig működik ez a módszer. Az `std::get` se járt sikerrel..
Egyenlőre csak ezt a megoldást láttam validnak.

2020-11-06 14:34 UTC, gradden commented on JSON.h
> +        return std::any_cast<T>(converted);
@hegyhati Másik csapatnál ugyanígy működik a get függvény, náluk oké volt ez a módszer.

2020-11-06 16:18 UTC, gradden commented
@hegyhati kicseréltem a return résznél az any_cast-et, így nem castol kétszer a függvényben

2020-11-08 12:51 UTC, hegyhati commented on JSON.h
> +        return std::any_cast<T>(converted);
Nem remlik, hogy meg egy ilyen ganyolast lattam volna, de ha igen, akkor attol itt nem lesz jo, csak ott siklottam at felette sajnos :-( De erdemes akkor nekik is szolni.

2020-11-08 12:55 UTC, hegyhati submitted a review, later dismissed
Tovabbra is ugyanaz a baj, cska most meg egy variantot is belekevertel. Osszevissza castolgatsz, any -> string -> variant (T) -> T. Ennek annyinak kellene lenni, hogy any -> T vagy ha szebben csinalod, variant -> T.

2020-11-08 12:55 UTC, hegyhati commented on JSON.h
> +        std::string value = std::any_cast<std::string>(map[key]);
a value-d any, amit itt fixen string-re castolsz, akarmi is volt.

2020-11-08 12:55 UTC, hegyhati commented on JSON.h
> +        std::variant<int, double, std::string> converted;
hogy itt minek csinalsz variantot, azt nem ertem.

2020-11-08 12:55 UTC, hegyhati commented on JSON.h
> +            converted=(std::stoi(value));
a value-d itt egy string, semmi ertelme itt variantba pakolni.

2020-11-08 15:28 UTC, gradden commented
@hegyhati Ahogy azt leírtam a kommentben is, most le commit-oltam azt a megoldást, aminek kéne lennie. De érthetetlen módon std::bad_any_cast hibát dob ki és elhasal. [(This solution fails for something and returns bad any cast)](https://github.com/Teaching-projects/SZE-MOSZE-2020-NullPointerException--Closed/runs/1370524554)
Vissza commitoltam azt a megoldást is, ami tényleg megtesz pár felesleges utat, de működik (és ugyanazt csinálja, mintha any_castelnék simán). 

**Megjegyzem,** hogy ez a ide-oda castolós megoldás már több csapat repójába bement a masterbe, és említés nélkül maradt náluk..

2020-11-08 16:21 UTC, hegyhati commented
A tobbi csapatot illeto dolgokrol irtam, nem mondom el ujra, de amugy dobalozas helyett akkor tessek linket kuldeni, es a masik csapatra is raszolok. Amugy eleg erthetoen megirtam mi a baj, egy fuggvenyen belul 3x castolod at ugyanazt 1 helyett. Ez egy teljesen gubanc kod, a fene se latja at, es az, hogy Te sem tudod, miert kapsz bad_cast-ot csak alatamasztja, hogy mennyire nem atlathato, a kod, amit irtal. Maga a map kellene, hogy vagy any vagy variant ertekeket taroljon, es abbol akkor anyvast/get segitsegevel egy castolassal kiszeded az adatot. Ha jol tetted bele. Ha eleve any<string>-kent tetted bele, akkor nyilvan nem fogod tudni any cast-tal int-re castolni. Ha nem erted, hogy mukodik az any, akkor ne hasznald. Voltak csapatok, akik variant vagy any nelkul is megoldottak, nem kell hozza ilyesmi feltetlenul. Olyan eszkozoket hasznalj, amiket ertesz, es atlagod, hogy mukodnek, nem csak egymasra hanysz 4 cast-ot, mert igy epp nem esik ossze a program. 

Mivel closed, ezert igazabol ez mar mindegy, de a jotanacsom ez tovabbra is. Erteni eloszor, aztan hasznalni.

2020-11-17 12:15 UTC, hegrobaa approved these changes
Hotfix keretein belül akkor ezt javítsuk ki majd.

2020-11-20 14:32 UTC, merged