Jsonparser
Teaching-projects/SZE-MOSZE-2020-NullPointerException pull request #3
Opened 2020-10-15 12:34 UTC by gradden

Created a new JsonParser class, this handles the file inputs and the stream inputs now. 
It contains an implemented Googletest in the "test" directory

2020-10-17 17:24 UTC, gradden commented
@wajzy készen vagyunk!

2020-10-18 15:40 UTC, wajzy requested changes
A jelzett pár aprósággal foglalkozz még egy kicsit!

2020-10-18 15:40 UTC, wajzy commented on Hero.cpp
> +        return Hero(Map["name"],stoi(Map["hp"]),stoi(Map["dmg"]));
Vagy?
Elég, ha egyetlen kulcs létezik a háromból?

2020-10-18 15:40 UTC, wajzy commented on JsonParser.cpp
> +    int szamlalo = 0;
Akkor ez egy olyan változó, ami sosem változik?

2020-10-18 15:40 UTC, wajzy commented on test/unit_test.cpp
> +}
OK, de legyen olyan teszteset is, ami azt vizsgálja, hogy egy hibás JSON bemenetre mit lépne a parzer.

2020-10-19 17:43 UTC, gradden commented
@wajzy Elvégeztem a kért módosításokat, implementáltam egy FailTestet is, ahol a wrong_json.json file hibásan van megadva.

2020-10-20 19:09 UTC, gradden commented
@wajzy készen vannak a Jsonparser-re vonatkozó javítások, illetve a confliktokat is megcsináltam. Kicsit összezavarodtam miközben összemostam a kettőt, de elméletileg ahogy látom, már nincsenek confliktok és sikeresen implementáltam a Jsonparser feladatot az attackspeed feladattal. Kérem nézze meg hogy mindent jól csináltam-e!

2020-10-22 17:19 UTC, wajzy approved these changes
Jó, legyen.

2020-10-22 17:19 UTC, merged