Documentation update
Teaching-projects/SZE-MOSZE-2020-NullPointerException pull request #8
Opened 2020-11-01 14:50 UTC by VarietyF

Added comments to the header files

2020-11-01 23:15 UTC, gboldi19 requested changes
Ha a `documentation` branch-et szeretnéd mergelni, akkor a page deploy merge után nem fog a nem létező branch-en történő push-ra elindulni (feltételezhetjük, hogy a branch törlésre kerül, miután bement). 

A másik észrevétel, hogy a gh pages-t nem te módosítod, hanem a config és doxygen fájlok együttesének futtatása folyamán generálódik nem? Mert ez esetben a gh pages nem a forrás, hanem az output, ami a forrásfájlokat tartalmazza a megjelenítéshez.

2020-11-01 23:19 UTC, gboldi19 commented
Erre a változtatásra, illetve fájlra gondoltam: cdb017fdc6df6d66eff43b8f78cfd0dab32dec67

2020-11-02 10:12 UTC, gradden commented
@gboldi19 Értem amit mondasz, de ha kitörlöm a documentation branchet a beállításból, akkor le se fog generálódni. Ha csak a mastert teszem bele, akkor meg suprise-ként fogom megtudni a végeredményt, amikor már masterbe mergeltem. De mivel kész a feladat, ezért átírom masterre. (Ha a _documentation_ branchen a jó kódot lefuttattam már egyszer (PR előtt), akkor a gh-pages branchet nem fogja semmi sem bántani ha masterre mergelem a _documentation_-t.)

2020-11-02 10:15 UTC, gradden requested changes

2020-11-02 10:15 UTC, gradden commented on .github/workflows/doxygen.yml
> +      - documentation
@VarietyF a documentation-t légyszi masterre cseréld, illetve a gh-pages nem szükséges oda

2020-11-02 15:22 UTC, balazs482 requested changes
A JsonParser.h-ban volt pár észrevétel. Nem muszáj mindennel egyetérteni és módosítani, de azért egy request changest nyomok.

2020-11-02 15:22 UTC, balazs482 commented on JsonParser.h
> +     * \return Returns the correct Map file of a hero if everythings good. If there's a problem we get a "Bad mapping" warning.
1. "hearo's" (elírás)
2. itt (és másik JsonParser-beli függvényben is) nem warning van

2020-11-02 15:22 UTC, balazs482 commented on JsonParser.h
>      static std::string WhitespaceCleanerAndFormatChecker(std::string&);
1. Ennél az egynél várnék egy pontos paraméter leírást, hogy egyértelmű legyen. Pláne, hogy csak típusokkal van deklarálva a headerben, szóval még a változónév sem árulkodik. Key és value is? Akár egyszerre az egész sor?

2. Egy egyszerű leírás is kellene, hogy mire ellenőriz? Hogy idézőjeleknél megfelelő string? Hogy nélkülük megfelelő numerikus érték (vagy boolian vagy null)?

2020-11-02 18:26 UTC, VarietyF commented
@gboldi19 @balazs482 @gradden felkerültek a kért módosítások

2020-11-02 18:36 UTC, balazs482 approved these changes
nice.

2020-11-02 18:41 UTC, gboldi19 approved these changes
@gradden review-ja számít, itt rossz helyre ment a change request. Ettől függetlenül approveolom

2020-11-02 18:46 UTC, gradden approved these changes
Szupi!

2020-11-02 18:47 UTC, merged