Makefile
Teaching-projects/SZE-MOSZE-2020-NullPointerException pull request #9
Opened 2020-11-01 15:03 UTC by gradden

@hegyhati elkészült a Makefile-os feladat!

2020-11-02 00:26 UTC, hegyhati requested changes

2020-11-02 00:26 UTC, hegyhati commented on .github/workflows/gtest.yml
> +      branches: [make]
es a masteren miert nem?!

2020-11-02 00:26 UTC, hegyhati commented on Makefile
> +
Header-ok! Lasd komment a csoportban.

2020-11-02 10:40 UTC, gradden commented
@hegyhati javítottam a hibákat!

2020-11-03 09:31 UTC, hegyhati approved these changes

2020-11-03 09:31 UTC, merged